// Generated by gencpp from file multirobot_map_merge/mapPair2tf.msg
// DO NOT EDIT!


#ifndef MULTIROBOT_MAP_MERGE_MESSAGE_MAPPAIR2TF_H
#define MULTIROBOT_MAP_MERGE_MESSAGE_MAPPAIR2TF_H

#include <ros/service_traits.h>


#include <multirobot_map_merge/mapPair2tfRequest.h>
#include <multirobot_map_merge/mapPair2tfResponse.h>


namespace multirobot_map_merge
{

struct mapPair2tf
{

typedef mapPair2tfRequest Request;
typedef mapPair2tfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mapPair2tf
} // namespace multirobot_map_merge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multirobot_map_merge::mapPair2tf > {
  static const char* value()
  {
    return "6fa85f9e352b2ce5cb5617042231d419";
  }

  static const char* value(const ::multirobot_map_merge::mapPair2tf&) { return value(); }
};

template<>
struct DataType< ::multirobot_map_merge::mapPair2tf > {
  static const char* value()
  {
    return "multirobot_map_merge/mapPair2tf";
  }

  static const char* value(const ::multirobot_map_merge::mapPair2tf&) { return value(); }
};


// service_traits::MD5Sum< ::multirobot_map_merge::mapPair2tfRequest> should match
// service_traits::MD5Sum< ::multirobot_map_merge::mapPair2tf >
template<>
struct MD5Sum< ::multirobot_map_merge::mapPair2tfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multirobot_map_merge::mapPair2tf >::value();
  }
  static const char* value(const ::multirobot_map_merge::mapPair2tfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multirobot_map_merge::mapPair2tfRequest> should match
// service_traits::DataType< ::multirobot_map_merge::mapPair2tf >
template<>
struct DataType< ::multirobot_map_merge::mapPair2tfRequest>
{
  static const char* value()
  {
    return DataType< ::multirobot_map_merge::mapPair2tf >::value();
  }
  static const char* value(const ::multirobot_map_merge::mapPair2tfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multirobot_map_merge::mapPair2tfResponse> should match
// service_traits::MD5Sum< ::multirobot_map_merge::mapPair2tf >
template<>
struct MD5Sum< ::multirobot_map_merge::mapPair2tfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multirobot_map_merge::mapPair2tf >::value();
  }
  static const char* value(const ::multirobot_map_merge::mapPair2tfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multirobot_map_merge::mapPair2tfResponse> should match
// service_traits::DataType< ::multirobot_map_merge::mapPair2tf >
template<>
struct DataType< ::multirobot_map_merge::mapPair2tfResponse>
{
  static const char* value()
  {
    return DataType< ::multirobot_map_merge::mapPair2tf >::value();
  }
  static const char* value(const ::multirobot_map_merge::mapPair2tfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTIROBOT_MAP_MERGE_MESSAGE_MAPPAIR2TF_H
